app:
  path: "/home/yuiseki/sinatra/arakawa/"

backend:
  type: "google_spreadsheet"
  sheet_key: your_spreadsheet_key

oauth:
  key: your_oauth_key
  secret: your_oauth_secret

site:
  url: "http://xn--fdr45z90g374a.jp/"
  title: "荒川智則.jp"
  desc: "東京の中央線に住んでいる無職と言われて思い浮かぶイメージのまんまの男。つまり、リベラルでポストモダンでオルタナティブでサブカルでロックなグランジでカート・コバーンを尊敬していて２７才で死ぬ定めにあると思っている。"
